In [14]:
## Importing the libraries required

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import MinMaxScaler
import math
## for feature selection

from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

## lINEAR REGRESSION

from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression

## It gives model fitment efficiency

from sklearn.metrics import r2_score       

## RANDOM FORREST

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor


## XGBOOST

from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

## KNN

from sklearn.neighbors import KNeighborsRegressor


## SVR

from sklearn.svm import SVR



## RMSE

from sklearn.metrics import mean_squared_error
from math import sqrt


## MAE

from sklearn.metrics import mean_absolute_error


## K FOLD

from sklearn.model_selection import KFold


## CROSS VALIDATION SCORE

from sklearn.model_selection import cross_val_score


## RANDOMIZED SEARCH CV

from sklearn.model_selection import RandomizedSearchCV



## STACKING ENSEMBLE

from sklearn.ensemble import StackingRegressor


## Display all the columns/fields of the dataframe

pd.pandas.set_option('display.max_columns',None)


## Display all the rows of the dataframe

pd.pandas.set_option('display.max_rows',None)



In [15]:
## Loading the independent/predictor variables

model_data=pd.read_csv('model_data.csv')

## Loading the dependent/target variable

target_var=pd.read_csv('y_train.csv')



test_data=pd.read_csv('test.csv')


In [16]:
## Viewing 'model_data' which contains the independent variables (i.e 21 features)

model_data.head(10)

MSSubClass  MSZoning  Neighborhood  OverallQual  YearRemodAdd  RoofStyle  \
0    0.235294      0.75      0.636364     0.666667      0.098361        0.0   
1    0.000000      0.75      0.500000     0.555556      0.524590        0.0   
2    0.235294      0.75      0.636364     0.666667      0.114754        0.0   
3    0.294118      0.75      0.727273     0.666667      0.606557        0.0   
4    0.235294      0.75      1.000000     0.777778      0.147541        0.0   
5    0.176471      0.75      0.409091     0.444444      0.245902        0.0   
6    0.000000      0.75      0.818182     0.777778      0.049180        0.0   
7    0.235294      0.75      0.545455     0.666667      0.606557        0.0   
8    0.176471      0.25      0.181818     0.666667      0.967213        0.0   
9    1.000000      0.75      0.136364     0.444444      0.967213        0.0   

   BsmtQual  BsmtExposure  HeatingQC  CentralAir  1stFlrSF  GrLivArea  \
0      0.75          0.25       1.00         1.0  0.356155   0.577712   
1      0.75          1.00       1.00         1.0  0.503056   0.470245   
2      0.75          0.50       1.00         1.0  0.383441   0.593095   
3      0.50          0.25       0.75         1.0  0.399941   0.579157   
4      0.75          0.75       1.00         1.0  0.466237   0.666523   
5      0.75          0.25       1.00         1.0  0.328654   0.497220   
6      1.00          0.75       1.00         1.0  0.614465   0.574387   
7      0.75          0.50       1.00         1.0  0.453465   0.648700   
8      0.50          0.25       0.75         1.0  0.423231   0.590710   
9      0.50          0.25       1.00         1.0  0.443067   0.414169   

   BsmtFullBath  KitchenQual  Fireplaces  FireplaceQu  GarageType  \
0      0.333333     0.666667    0.000000          0.2         0.8   
1      0.000000     0.333333    0.333333          0.6         0.8   
2      0.333333     0.666667    0.333333          0.6         0.8   
3      0.333333     0.666667    0.333333          0.8         0.4   
4      0.333333     0.666667    0.333333          0.6         0.8   
5      0.333333     0.333333    0.000000          0.2         0.8   
6      0.333333     0.666667    0.333333          0.8         0.8   
7      0.333333     0.333333    0.666667          0.6         0.8   
8      0.000000     0.333333    0.666667          0.6         0.4   
9      0.333333     0.333333    0.666667          0.6         0.8   

   GarageFinish  GarageCars  PavedDrive  SaleCondition  
0      0.666667        0.50         1.0           0.75  
1      0.666667        0.50         1.0           0.75  
2      0.666667        0.50         1.0           0.75  
3      0.333333        0.75         1.0           0.00  
4      0.666667        0.75         1.0           0.75  
5      0.333333        0.50         1.0           0.75  
6      0.666667        0.50         1.0           0.75  
7      0.666667        0.50         1.0           0.75  
8      0.333333        0.50         1.0           0.00  
9      0.666667        0.25         1.0           0.75

In [17]:
## Checking the shape of the dataframe

model_data.shape

(1460, 21)

In [18]:
## Getting details about each features in the dataframe

model_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     1460 non-null   float64
 1   MSZoning       1460 non-null   float64
 2   Neighborhood   1460 non-null   float64
 3   OverallQual    1460 non-null   float64
 4   YearRemodAdd   1460 non-null   float64
 5   RoofStyle      1460 non-null   float64
 6   BsmtQual       1460 non-null   float64
 7   BsmtExposure   1460 non-null   float64
 8   HeatingQC      1460 non-null   float64
 9   CentralAir     1460 non-null   float64
 10  1stFlrSF       1460 non-null   float64
 11  GrLivArea      1460 non-null   float64
 12  BsmtFullBath   1460 non-null   float64
 13  KitchenQual    1460 non-null   float64
 14  Fireplaces     1460 non-null   float64
 15  FireplaceQu    1460 non-null   float64
 16  GarageType     1460 non-null   float64
 17  GarageFinish   1460 non-null   float64
 18  GarageCa

In [19]:
## Checking whether the dtaframe has any NAN values 

model_data.isnull().sum()

MSSubClass       0
MSZoning         0
Neighborhood     0
OverallQual      0
YearRemodAdd     0
RoofStyle        0
BsmtQual         0
BsmtExposure     0
HeatingQC        0
CentralAir       0
1stFlrSF         0
GrLivArea        0
BsmtFullBath     0
KitchenQual      0
Fireplaces       0
FireplaceQu      0
GarageType       0
GarageFinish     0
GarageCars       0
PavedDrive       0
SaleCondition    0
dtype: int64

In [20]:
## Checking 'target_var' which contains the dependent varaible values

target_var.head(10)

SalePrice
0  12.247694
1  12.109011
2  12.317167
3  11.849398
4  12.429216
5  11.870600
6  12.634603
7  12.206073
8  11.774520
9  11.678440

In [21]:
## Checking the shape of the dataframe

target_var.shape

(1460, 1)

In [22]:
## Getting details about the feature present inside the dataframe

target_var.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   SalePrice  1460 non-null   float64
dtypes: float64(1)
memory usage: 11.5 KB


In [23]:
## Checking whether the dataframe has any NAN values

target_var.isnull().sum()

SalePrice    0
dtype: int64

In [24]:
##  Define X and y

X=model_data.loc[:,:]
y=target_var.SalePrice

In [12]:
X.tail(10)

MSSubClass  MSZoning  Neighborhood  OverallQual  YearRemodAdd  \
1450    0.411765      0.75      0.363636     0.444444      0.590164   
1451    0.000000      0.75      0.818182     0.777778      0.016393   
1452    0.941176      0.25      0.227273     0.444444      0.032787   
1453    0.000000      0.75      0.409091     0.444444      0.016393   
1454    0.000000      1.00      0.818182     0.666667      0.081967   
1455    0.235294      0.75      0.590909     0.555556      0.131148   
1456    0.000000      0.75      0.545455     0.555556      0.377049   
1457    0.294118      0.75      0.727273     0.666667      0.081967   
1458    0.000000      0.75      0.363636     0.444444      0.245902   
1459    0.000000      0.75      0.227273     0.444444      0.721311   

      RoofStyle  BsmtQual  BsmtExposure  HeatingQC  CentralAir  1stFlrSF  \
1450        0.0      0.75          0.25       0.50         1.0  0.373438   
1451        0.0      0.75          0.25       1.00         1.0  0.587621   
1452        0.0      0.75          1.00       0.75         1.0  0.441306   
1453        0.0      0.75          0.25       1.00         1.0  0.464581   
1454        0.0      0.75          0.25       1.00         1.0  0.490557   
1455        0.0      0.75          0.25       1.00         1.0  0.396777   
1456        0.0      0.75          0.25       0.50         1.0  0.690872   
1457        0.0      0.50          0.25       1.00         1.0  0.480189   
1458        1.0      0.50          0.50       0.75         1.0  0.443419   
1459        0.0      0.50          0.25       0.75         1.0  0.501253   

      GrLivArea  BsmtFullBath  KitchenQual  Fireplaces  FireplaceQu  \
1450   0.594282      0.000000     0.333333    0.000000          0.2   
1451   0.549294      0.000000     1.000000    0.333333          0.8   
1452   0.412522      0.333333     0.333333    0.000000          0.2   
1453   0.434279      0.000000     0.333333    0.000000          0.2   
1454   0.458561      0.333333     0.666667    0.000000          0.2   
1455   0.564433      0.000000     0.333333    0.333333          0.6   
1456   0.645810      0.333333     0.333333    0.666667          0.6   
1457   0.688669      0.000000     0.666667    0.666667          0.8   
1458   0.414497      0.333333     0.666667    0.000000          0.2   
1459   0.468559      0.333333     0.333333    0.000000          0.2   

      GarageType  GarageFinish  GarageCars  PavedDrive  SaleCondition  
1450         0.0      0.000000        0.00         1.0           0.75  
1451         0.8      1.000000        0.75         1.0           1.00  
1452         0.6      1.000000        0.50         1.0           0.75  
1453         0.0      0.000000        0.00         1.0           0.00  
1454         0.8      0.666667        0.50         1.0           0.75  
1455         0.8      0.666667        0.50         1.0           0.75  
1456         0.8      0.333333        0.50         1.0           0.75  
1457         0.8      0.666667        0.25         1.0           0.75  
1458         0.8      0.333333        0.25         1.0           0.75  
1459         0.8      1.000000        0.25         1.0           0.75

In [13]:
y.tail(10)

1450    11.820410
1451    12.567551
1452    11.884489
1453    11.344507
1454    12.128111
1455    12.072541
1456    12.254863
1457    12.493130
1458    11.864462
1459    11.901583
Name: SalePrice, dtype: float64

In [14]:
type(X)

pandas.core.frame.DataFrame

In [15]:
type(y)

pandas.core.series.Series

### MODEL TRAINING USING TRAIN TEST SPLIT

In [16]:
## Train Test Split 

X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.3,random_state=10)


In [17]:
## Checking X_train, X_test, y_train, y_test shapes

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (1022, 21)
X_test shape: (438, 21)
y_train shape: (1022,)
y_test shape: (438,)


In [18]:
## Function for calculating model score 

def get_model_score (model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return (model.score(X_test,y_test))

In [19]:
## Function for calcutating  r2_score of the model

def get_r2_score (model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    y_predict= model.predict(X_test)
    return (r2_score(y_test,y_predict))

In [20]:
## Function for calcutating rmse (Root Mean Square Error) score of the model

def get_rmse_score (model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    y_predict= model.predict(X_test)
    rmse = sqrt(mean_squared_error(y_test,y_predict))
    return (rmse)

In [21]:
## Function for calcutating mae (Mean Absolute Error) score of the model

def get_mae_score (model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    y_predict= model.predict(X_test)
    return (mean_absolute_error(y_test, y_predict))

In [22]:
## Function for displaying y_train and y_predict values 

def get_y_train_y_predict (model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    y_predict= model.predict(X_test)
    return (y_train[0:5],y_predict[0:5])

### LINEAR REGRESSION

#### CALCULATING  MODEL SCORE,  R2_SCORE,  RMSE(ROOT MEAN SQUARE ERROR),  MAE(MEAN ABSOLUTE ERROR),  Y_TRAIN AND   Y_PREDICT   FOR LINEAR REGRESSION MODEL

In [23]:
## Calculating the model score 

get_model_score(LinearRegression(),X_train,X_test,y_train,y_test)

0.9045186607744512

In [24]:
## Calculating r2_score for the model

get_r2_score(LinearRegression(),X_train,X_test,y_train,y_test)

0.9045186607744512

In [25]:
## Calculating rmse score for the model

get_rmse_score(LinearRegression(),X_train,X_test,y_train,y_test)

0.12623154331407813

In [26]:
## Calculating mean absolute error for the model

get_mae_score(LinearRegression(),X_train,X_test,y_train,y_test)

0.09617033811414802

In [28]:
## Displaying and comparing y_train and y_predict values

get_y_train_y_predict(LinearRegression(),X_train,X_test,y_train,y_test)

(912    11.385092
 373    11.719940
 20     12.692503
 800    12.206073
 152    12.154779
 Name: SalePrice, dtype: float64,
 array([12.01124377, 12.33423667, 11.71087192, 11.88051241, 12.66178648]))

In [29]:
## Viewing all model evaluation metric values for Linear Regression 

result_linear_traintest =pd.DataFrame({'model_score': [get_model_score(LinearRegression(),X_train,X_test,y_train,y_test)],
                                       'r2_score':[get_r2_score(LinearRegression(),X_train,X_test,y_train,y_test)],
                                       'rmse':[get_rmse_score(LinearRegression(),X_train,X_test,y_train,y_test)],
                                       'mae':[get_mae_score(LinearRegression(),X_train,X_test,y_train,y_test)]},
                                       index=['Linear Regression'])

# result_linear_traintest

### RANDOM FOREST

#### CALCULATING  MODEL SCORE,  R2_SCORE,  RMSE(ROOT MEAN SQUARE ERROR),  MAE(MEAN ABSOLUTE ERROR),  Y_TRAIN AND   Y_PREDICT   FOR RANDOM FOREST MODEL

In [30]:
## Calculating the model score 

get_model_score(RandomForestRegressor(n_estimators=200,random_state=10),X_train,X_test,y_train,y_test)

0.8780674302658347

In [31]:
## Calculating r2_score for the model

get_r2_score(RandomForestRegressor(n_estimators=200,random_state=10),X_train,X_test,y_train,y_test)

0.8780674302658347

In [32]:
## Calculating rmse score for the model

get_rmse_score(RandomForestRegressor(n_estimators=200,random_state=10),X_train,X_test,y_train,y_test)

0.14264892540006113

In [33]:
## Calculating mean absolute error for the model

get_mae_score(RandomForestRegressor(n_estimators=200,random_state=10),X_train,X_test,y_train,y_test)

0.10319791169608312

In [34]:
## Displaying and comparing y_train and y_predict values

get_y_train_y_predict(RandomForestRegressor(n_estimators=200,random_state=10),X_train,X_test,y_train,y_test)

(912    11.385092
 373    11.719940
 20     12.692503
 800    12.206073
 152    12.154779
 Name: SalePrice, dtype: float64,
 array([11.90255175, 12.24917183, 11.75254117, 11.91223594, 12.70656328]))

In [35]:
## Viewing all model evaluation metric values for Random Forest 

result_rf_traintest =pd.DataFrame({'model_score': [get_model_score(RandomForestRegressor(n_estimators=200,random_state=10),X_train,X_test,y_train,y_test)],
                                   'r2_score':[get_r2_score(RandomForestRegressor(n_estimators=200,random_state=10),X_train,X_test,y_train,y_test)],
                                    'rmse':[get_rmse_score(RandomForestRegressor(n_estimators=200,random_state=10),X_train,X_test,y_train,y_test)],
                                    'mae':[get_mae_score(RandomForestRegressor(n_estimators=200,random_state=10),X_train,X_test,y_train,y_test)]},
                                    index=['Random Forest'])

# result_rf_traintest

### XGBOOST

#### CALCULATING  MODEL SCORE,  R2_SCORE,  RMSE(ROOT MEAN SQUARE ERROR),  MAE(MEAN ABSOLUTE ERROR),  Y_TRAIN AND   Y_PREDICT   FOR XGBOOST MODEL

In [36]:
## Calculating the model score 

get_model_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X_train,X_test,y_train,y_test)

0.9039407400604521

In [37]:
## Calculating r2_score for the model

get_r2_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X_train,X_test,y_train,y_test)

0.9039407400604521

In [38]:
## Calculating rmse score for the model

get_rmse_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X_train,X_test,y_train,y_test)

0.12661298835883292

In [39]:
## Calculating mean absolute error for the model

get_mae_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X_train,X_test,y_train,y_test)

0.09390975344967042

In [40]:
## Displaying and comparing y_train and y_predict values

get_y_train_y_predict(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X_train,X_test,y_train,y_test)

(912    11.385092
 373    11.719940
 20     12.692503
 800    12.206073
 152    12.154779
 Name: SalePrice, dtype: float64,
 array([11.967659, 12.288242, 11.771351, 11.862206, 12.660163],
       dtype=float32))

In [41]:
## Viewing all model evaluation metric values for XGBOOST 

result_XGBOOST_traintest =pd.DataFrame({'model_score': [get_model_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X_train,X_test,y_train,y_test)],
                                       'r2_score':[get_r2_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X_train,X_test,y_train,y_test)],
                                       'rmse':[get_rmse_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X_train,X_test,y_train,y_test)],
                                       'mae':[get_mae_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X_train,X_test,y_train,y_test)]},
                                       index=['XGBOOST'])

# result_XGBOOST_traintest

### KNN

#### CALCULATING  MODEL SCORE,  R2_SCORE,  RMSE(ROOT MEAN SQUARE ERROR),  MAE(MEAN ABSOLUTE ERROR),  Y_TRAIN AND   Y_PREDICT   FOR KNN MODEL

In [42]:
## Calculating the model score 

get_model_score(KNeighborsRegressor(n_neighbors=7),X_train,X_test,y_train,y_test)

0.8034588938853509

In [43]:
## Calculating r2_score for the model

get_r2_score(KNeighborsRegressor(n_neighbors=7),X_train,X_test,y_train,y_test)

0.8034588938853509

In [44]:
## Calculating rmse score for the model

get_rmse_score(KNeighborsRegressor(n_neighbors=7),X_train,X_test,y_train,y_test)

0.18110704268636188

In [45]:
## Calculating mean absolute error for the model

get_mae_score(KNeighborsRegressor(n_neighbors=7),X_train,X_test,y_train,y_test)

0.13347669558654582

In [46]:
## Displaying and comparing y_train and y_predict values

get_y_train_y_predict(KNeighborsRegressor(n_neighbors=7),X_train,X_test,y_train,y_test)

(912    11.385092
 373    11.719940
 20     12.692503
 800    12.206073
 152    12.154779
 Name: SalePrice, dtype: float64,
 array([11.98047689, 12.39617801, 11.90017953, 11.93539986, 12.4910143 ]))

In [47]:
## Viewing all model evaluation metric values for KNN 

result_KNN_traintest =pd.DataFrame({'model_score': [get_model_score(KNeighborsRegressor(n_neighbors=7),X_train,X_test,y_train,y_test)],
                                       'r2_score':[get_r2_score(KNeighborsRegressor(n_neighbors=7),X_train,X_test,y_train,y_test)],
                                       'rmse':[get_rmse_score(KNeighborsRegressor(n_neighbors=7),X_train,X_test,y_train,y_test)],
                                       'mae':[get_mae_score(KNeighborsRegressor(n_neighbors=7),X_train,X_test,y_train,y_test)]},
                                       index=['KNN'])

# result_KNN_traintest

### SVR

#### CALCULATING  MODEL SCORE,  R2_SCORE,  RMSE(ROOT MEAN SQUARE ERROR),  MAE(MEAN ABSOLUTE ERROR),  Y_TRAIN AND   Y_PREDICT   FOR SVR MODEL

In [48]:
## Calculating the model score  #C--0.1 to 1000 #gamma---0.01 to 10

get_model_score(SVR(C=4,gamma=0.2,kernel='rbf'),X_train,X_test,y_train,y_test)

0.894998826770466

In [49]:
## Calculating r2_score for the model

get_r2_score(SVR(C=4,gamma=0.2,kernel='rbf'),X_train,X_test,y_train,y_test)

0.894998826770466

In [50]:
## Calculating rmse score for the model

get_rmse_score(SVR(C=4,gamma=0.2,kernel='rbf'),X_train,X_test,y_train,y_test)

0.13237492190183475

In [51]:
## Calculating mean absolute error for the model

get_mae_score(SVR(C=4,gamma=0.2,kernel='rbf'),X_train,X_test,y_train,y_test)

0.100169603914134

In [52]:
## Displaying and comparing y_train and y_predict values

get_y_train_y_predict(SVR(C=4,gamma=0.2,kernel='rbf'),X_train,X_test,y_train,y_test)

(912    11.385092
 373    11.719940
 20     12.692503
 800    12.206073
 152    12.154779
 Name: SalePrice, dtype: float64,
 array([11.93315003, 12.28873862, 11.77078287, 11.86425653, 12.66351356]))

In [53]:
## Viewing all model evaluation metric values for SVR

result_SVR_traintest =pd.DataFrame({'model_score': [get_model_score(SVR(C=4,gamma=0.2,kernel='rbf'),X_train,X_test,y_train,y_test)],
                                       'r2_score':[get_r2_score(SVR(C=4,gamma=0.2,kernel='rbf'),X_train,X_test,y_train,y_test)],
                                       'rmse':[get_rmse_score(SVR(C=4,gamma=0.2,kernel='rbf'),X_train,X_test,y_train,y_test)],
                                       'mae':[get_mae_score(SVR(C=4,gamma=0.2,kernel='rbf'),X_train,X_test,y_train,y_test)]},
                                       index=['SVR'])

# result_SVR_traintest

In [168]:
## Comparing all the model evaluation metric values for train test split method for different machine learning models

result_traintest=pd.concat([result_linear_traintest,result_rf_traintest,result_XGBOOST_traintest,result_KNN_traintest,
                            result_SVR_traintest],
                           axis=0)

## Displaying the final result in ascending order by column names

result_traintest.sort_values(by=['model_score','r2_score'],ascending=False)

model_score  r2_score      rmse       mae
Linear Regression     0.904519  0.904519  0.126232  0.096170
XGBOOST               0.903941  0.903941  0.126613  0.093910
SVR                   0.894999  0.894999  0.132375  0.100170
Random Forest         0.878067  0.878067  0.142649  0.103198
KNN                   0.803459  0.803459  0.181107  0.133477

### MODEL TRAINING USING CROSS VALIDATION

In [55]:
## Loading the independent/predictor variables

model_data=pd.read_csv('model_data.csv')

## Loading the dependent/target variable

target_var=pd.read_csv('y_train.csv')

In [56]:
##  4. Define X and y

X=model_data.loc[:,:]
y=target_var.SalePrice

### LINEAR REGRESSION

#### Calculating the cross validation score for Linear Regression model

In [57]:
cross_val_score(LinearRegression(),X,y,cv=10)

array([0.89278531, 0.90807213, 0.90241061, 0.8701609 , 0.88408339,
       0.89895816, 0.88405797, 0.88893272, 0.80872116, 0.87082485])

In [58]:
cross_val_score(LinearRegression(),X,y,cv=10).mean()

0.8809007195097893

### RANDOM FOREST

#### Calculating the cross validation score for Random Forest model 

In [59]:
cross_val_score(RandomForestRegressor(n_estimators=200,random_state=10),X,y,cv=10)

array([0.86447141, 0.8974821 , 0.889042  , 0.83998966, 0.87069778,
       0.88937201, 0.89536344, 0.89275378, 0.87862965, 0.82357128])

In [60]:
cross_val_score(RandomForestRegressor(n_estimators=200,random_state=10),X,y,cv=10).mean()

0.8741373110130544

### XGBOOST

#### Calculating the cross validation score for XGBOOST model 

In [61]:
cross_val_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X,y,cv=10)

array([0.88800959, 0.91027847, 0.89839597, 0.88021405, 0.88525387,
       0.91617626, 0.90987396, 0.89570805, 0.8770334 , 0.85438231])

In [62]:
cross_val_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=200),X,y,cv=10).mean()

0.8915325932873662

### KNN

#### Calculating the cross validation score for KNN model 

In [63]:
cross_val_score(KNeighborsRegressor(n_neighbors=7),X,y,cv=10)

array([0.831171  , 0.81591608, 0.82008086, 0.79234589, 0.79821717,
       0.81148038, 0.76298357, 0.80346604, 0.76053519, 0.76550311])

In [64]:
cross_val_score(KNeighborsRegressor(n_neighbors=7),X,y,cv=10).mean()

0.7961699298686991

### SVR

#### Calculating the cross validation score for SVR model

In [65]:
cross_val_score(SVR(C=4,gamma=0.2,kernel='rbf'),X,y,cv=10)

array([0.88894262, 0.91944731, 0.89542299, 0.87343852, 0.89262201,
       0.91492951, 0.88952842, 0.88611285, 0.84227032, 0.86676284])

In [66]:
cross_val_score(SVR(C=4,gamma=0.2,kernel='rbf'),X,y,cv=10).mean()

0.8869477387685534

In [176]:
## Converting cross validation score of Linear model into dataframe

result_linear_crossval =pd.DataFrame({'cross_val_score': [cross_val_score(LinearRegression(),X,y,cv=10).mean()]},
                                       index=['Linear Regression'])

## Converting cross validation score of Random Forest model into dataframe

result_rf_crossval =pd.DataFrame({'cross_val_score': [cross_val_score(RandomForestRegressor(n_estimators=200,random_state=10),
                                                      X,y,cv=10).mean()]},
                                   index=['Random Forest'])

## Converting cross validation score of XGBOOST model into dataframe

result_XGBOOST_crossval =pd.DataFrame({'cross_val_score': [cross_val_score(XGBRegressor(learning_rate=0.05,random_state=10,
                                                          n_estimators=200),X,y,cv=10).mean()]},
                                       index=['XGBOOST'])

## Converting cross validation score of KNN model into dataframe

result_KNN_crossval =pd.DataFrame({'cross_val_score': [cross_val_score(KNeighborsRegressor(n_neighbors=7),X,y,cv=10).mean()]},
                                       index=['KNN'])


## Converting cross validation score of SVR model into dataframe

result_SVR_crossval =pd.DataFrame({'cross_val_score': [cross_val_score(SVR(C=4,gamma=0.2,kernel='rbf'),X,y,cv=10).mean()]},
                                       index=['SVR'])


## Comparing all the cross validation scores for cross validation method for different machine learning models

result_crossval=pd.concat([result_linear_crossval,result_rf_crossval,result_XGBOOST_crossval,result_KNN_crossval,result_SVR_crossval],
                          axis=0)

## Displaying the final result in ascending order by column names

result_crossval.sort_values(by=['cross_val_score'],ascending=False)

cross_val_score
XGBOOST                   0.891533
SVR                       0.886948
Linear Regression         0.880901
Random Forest             0.874137
KNN                       0.796170

In [179]:
## Viewing and comparing all the model evaluation metrics values of different models without hyperparameter optimization

result_without_hyperparamtune=result_traintest.merge(result_crossval, left_index=True, right_index=True)

# result_without_hyperparamtune=result_crossval.merge(result_traintest)

result_without_hyperparamtune

model_score  r2_score      rmse       mae  cross_val_score
Linear Regression     0.904519  0.904519  0.126232  0.096170         0.880901
Random Forest         0.878067  0.878067  0.142649  0.103198         0.874137
XGBOOST               0.903941  0.903941  0.126613  0.093910         0.891533
KNN                   0.803459  0.803459  0.181107  0.133477         0.796170
SVR                   0.894999  0.894999  0.132375  0.100170         0.886948

### HYPER PARAMETER OPTIMIZATION FOR RANDOM FOREST

#### RANDOMISED SEARCH CV

In [82]:
## Number of trees in random forest

n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]

## Defining the number of features to be considered at every split

max_features = ['auto', 'sqrt','log2']

## Defining maximum number of levels in tree

max_depth = [int(x) for x in np.linspace(10, 1000,10)]

## Defining minimum number of samples required to split a node

min_samples_split = [2, 5, 10,14]

## Defining minimum number of samples required at each leaf node

min_samples_leaf = [1, 2, 4,6,8]


random_grid_rf = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               }

print(random_grid_rf)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8]}


#### FITTING RANDOMIZED SEARCH CV TO TRAIN TEST SPLIT DATA

In [69]:
rf=RandomForestRegressor()
rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid_rf,n_iter=10,cv=4,verbose=2,
                               random_state=10,n_jobs=-1)
### fit the randomized model
rf_randomcv.fit(X_train,y_train)

Fitting 4 folds for each of 10 candidates, totalling 40 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   22.9s
[Parallel(n_jobs=-1)]: Done  40 out of  40 | elapsed:   34.9s finished


RandomizedSearchCV(cv=4, estimator=RandomForestRegressor(), n_jobs=-1,
                   param_distributions={'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=10, verbose=2)

#### FINDING THE BEST PARAMETER VALUES FOR DIFFERENT 'n_iter' AND 'cv'

In [77]:
rf_randomcv.best_params_ #for n_iter=10,cv=4  

{'n_estimators': 2000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 340}

#### Applying tuned hyper parameters using train test split technique for Random Forest

In [75]:
## For n_iter=10,cv=4,RANDOM FOREST,(n_estimators=2000,max_depth=340, max_features='sqrt', min_samples_leaf=1,
## min_samples_split= 2),RANDOM STATE=10


## Calculating the model score with tuned hyperparameters

get_model_score(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                      max_features= 'sqrt',max_depth= 340,random_state=10),X_train,X_test,y_train,y_test)

0.8870491847954503

In [76]:
## For n_iter=10,cv=4,RANDOM FOREST,(n_estimators=2000,max_depth=340, max_features='sqrt', min_samples_leaf=1,
## min_samples_split= 2),RANDOM STATE=10

## Calculating r2_score for the model with tuned hyperparameters

get_r2_score(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                   max_features= 'sqrt',max_depth= 340,random_state=10),X_train,X_test,y_train,y_test)

0.8870491847954503

In [77]:
## For n_iter=10,cv=4,RANDOM FOREST,(n_estimators=2000,max_depth=340, max_features='sqrt', min_samples_leaf=1,
## min_samples_split= 2),RANDOM STATE=10

## Calculating rmse score for the model with tuned hyperparameters

get_rmse_score(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                     max_features= 'sqrt',max_depth= 340,random_state=10),X_train,X_test,y_train,y_test)

0.1372945588341894

In [78]:
## For n_iter=10,cv=4,RANDOM FOREST,(n_estimators=2000,max_depth=340, max_features='sqrt', min_samples_leaf=1,
## min_samples_split= 2),RANDOM STATE=10

## Calculating mean absolute error for the model with tuned hyperparameters

get_mae_score(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                    max_features= 'sqrt',max_depth= 340,random_state=10),X_train,X_test,y_train,y_test)



0.09698778683878008

In [79]:
## For n_iter=10,cv=4,RANDOM FOREST,(n_estimators=2000,max_depth=340, max_features='sqrt', min_samples_leaf=1,
## min_samples_split= 2),RANDOM STATE=10

## Displaying and comparing y_train and y_predict values with tuned hyperparameters

get_y_train_y_predict(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                    max_features= 'sqrt',max_depth= 340,random_state=10),X_train,X_test,y_train,y_test)

(912    11.385092
 373    11.719940
 20     12.692503
 800    12.206073
 152    12.154779
 Name: SalePrice, dtype: float64,
 array([11.98559888, 12.25314911, 11.78135374, 11.92500758, 12.69526753]))

In [80]:
## Viewing all model evaluation metric values for Random Forest using tuned hyperparameters 

result_rf_traintest_hyperparamtune =pd.DataFrame({'model_score': [get_model_score(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                                                  max_features= 'sqrt',max_depth= 340,random_state=10),X_train,X_test,y_train,y_test)],
                                       
                                                  'r2_score':[get_r2_score(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                                              max_features= 'sqrt',max_depth= 340,random_state=10),X_train,X_test,y_train,y_test)],
                                                  
                                                  'rmse':[get_rmse_score(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                                          max_features= 'sqrt',max_depth= 340,random_state=10),X_train,X_test,y_train,y_test)],
                                                  
                                                  'mae':[get_mae_score(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                                         max_features= 'sqrt',max_depth= 340,random_state=10),X_train,X_test,y_train,y_test)]},
                                       
                                                  index=['Random Forest Hyperparameter Tuned'])

# result_rf_traintest_hyperparamtune

model_score  r2_score      rmse       mae
Random Forest Hyperparameter Tuned     0.887049  0.887049  0.137295  0.096988

#### FITTING RANDOMIZED SEARCH CV TO X,y DIRECTLY (WITHOUT TRAIN TEST SPLITING)

In [83]:
rf=RandomForestRegressor()
rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid_rf,n_iter=10,cv=4,verbose=2,
                               random_state=10,n_jobs=-1)
### fit the randomized model
rf_randomcv.fit(X,y)

Fitting 4 folds for each of 10 candidates, totalling 40 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   31.8s
[Parallel(n_jobs=-1)]: Done  40 out of  40 | elapsed:   48.5s finished


RandomizedSearchCV(cv=4, estimator=RandomForestRegressor(), n_jobs=-1,
                   param_distributions={'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=10, verbose=2)

#### FINDING THE BEST PARAMETER VALUES FOR DIFFERENT 'n_iter' AND 'cv'

In [84]:
rf_randomcv.best_params_ # for n_iter=10,cv=4 

{'n_estimators': 2000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 340}

#### Applying tuned hyper parameters using Cross Validation technique for Random Forest

In [85]:
## For n_iter=10,cv=4,RANDOM FOREST,(n_estimators=2000,max_depth=340, max_features='sqrt', min_samples_leaf=1,
## 'min_samples_split': 2),RANDOM STATE=10

cross_val_score(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                      max_features= 'sqrt',max_depth= 340,random_state=10),X,y,cv=10).mean()

0.8874231792387043

In [86]:
## Converting cross validation score of Random Forest model with tuned hyperparameters into dataframe

result_rf_crossval_hyperparamtune =pd.DataFrame({'cross_val_score': [cross_val_score(RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                                                    max_features= 'sqrt',max_depth= 340,random_state=10),X,y,cv=10).mean()]},
                                       index=['Random Forest Hyperparameter Tuned'])


cross_val_score
Random Forest Hyperparameter Tuned         0.887423

In [87]:
## Viewing all the model evaluation metric values and cross validation score for Random Forest 
## using tuned hyperparameters

result_rf_hyperparamtune=pd.concat([result_rf_traintest_hyperparamtune,result_rf_crossval_hyperparamtune],
                          axis=1)



model_score  r2_score      rmse       mae  \
Random Forest Hyperparameter Tuned     0.887049  0.887049  0.137295  0.096988   

                                    cross_val_score  
Random Forest Hyperparameter Tuned         0.887423

### HYPERARAMETER OPTIMIZATION FOR XGBOOOST

In [88]:
## Defining the different hperparameter values

params_xgboost={
    
    'n_estimators'     :[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000],
    'learning_rate'    :[0.05,0.10,0.15,0.20,0.25,0.30],
    'max_depth'        :[3,4,5,6,8,10,12,15],
    'min_child_weight' :[1,3,5,7],
    'gamma'            :[0.1,0.2,0.3,0.4],
    'colsample_bytree' :[0.3,0.4,0.5,0.7]
}

print(params_xgboost)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'learning_rate': [0.05, 0.1, 0.15, 0.2, 0.25, 0.3], 'max_depth': [3, 4, 5, 6, 8, 10, 12, 15], 'min_child_weight': [1, 3, 5, 7], 'gamma': [0.1, 0.2, 0.3, 0.4], 'colsample_bytree': [0.3, 0.4, 0.5, 0.7]}


### Fitting Randomized Search CV For Train Test Split data

In [103]:
xgboost_randomcv=RandomizedSearchCV(XGBRegressor(),param_distributions=params_xgboost,n_iter=50,n_jobs=1,cv=10,verbose=3)

xgboost_randomcv.fit(X_train,y_train)

Fitting 10 folds for each of 50 candidates, totalling 500 fits
[CV] n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5, score=0.898, total=   1.0s
[CV] n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.9s remaining:    0.0s


[CV]  n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5, score=0.848, total=   0.9s
[CV] n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5 


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.8s remaining:    0.0s


[CV]  n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5, score=0.800, total=   0.9s
[CV] n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5 
[CV]  n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5, score=0.890, total=   0.9s
[CV] n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5 
[CV]  n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5, score=0.810, total=   0.9s
[CV] n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5 
[CV]  n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5, score=0.835, total=   0.9s
[CV] n_estimators=1600, min_child_weight=7, max_depth=8, learning_rate=0.3, gamma=0.4, colsample_bytree=0.5 
[CV]  n_estimato

[Parallel(n_jobs=1)]: Done 500 out of 500 | elapsed:  7.0min finished


RandomizedSearchCV(cv=10,
                   estimator=XGBRegressor(base_score=None, booster=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, gamma=None,
                                          gpu_id=None, importance_type='gain',
                                          interaction_constraints=None,
                                          learning_rate=None,
                                          max_delta_step=None, max_depth=None,
                                          min_child_weight=None, missing=nan,
                                          monotone_constraints=None,
                                          n_estimators=100,...
                                          scale_pos_weight=None, subsample=None,
                                          tree_method=None,
                                          validate

#### FINDING THE BEST PARAMETER VALUES FOR DIFFERENT 'n_iter' AND 'cv'

In [104]:
xgboost_randomcv.best_params_ ## n_iter=50,cv=10  BEST

{'n_estimators': 2000,
 'min_child_weight': 3,
 'max_depth': 8,
 'learning_rate': 0.05,
 'gamma': 0.1,
 'colsample_bytree': 0.3}

#### Applying tuned hyper parameters using train test split technique for Xgboost

In [89]:
## n_iter=50,cv=10

## Calculating the model score with tuned hyperparameters

get_model_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=2000,min_child_weight=3,max_depth=8,
                             gamma=0.1,colsample_bytree=0.3),X_train,X_test,y_train,y_test)

0.9017014854420474

In [90]:
## n_iter=50,cv=10

## Calculating r2_score for the model with tuned hyperparameters

get_r2_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=2000,min_child_weight=3,max_depth=8,
                             gamma=0.1,colsample_bytree=0.3),X_train,X_test,y_train,y_test)

0.9017014854420474

In [91]:
## n_iter=50,cv=10

## Calculating rmse score for the model with tuned hyperparameters

get_rmse_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=2000,min_child_weight=3,max_depth=8,
                             gamma=0.1,colsample_bytree=0.3),X_train,X_test,y_train,y_test)

0.1280802358293695

In [92]:
## n_iter=50,cv=10

## Calculating mean absolute error for the model with tuned hyperparameters

get_mae_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=2000,min_child_weight=3,max_depth=8,
                             gamma=0.1,colsample_bytree=0.3),X_train,X_test,y_train,y_test)


0.09500642875403731

In [93]:
## n_iter=50,cv=10

## Displaying and comparing y_train and y_predict values with tuned hyperparameters

get_y_train_y_predict(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=2000,min_child_weight=3,max_depth=8,
                             gamma=0.1,colsample_bytree=0.3),X_train,X_test,y_train,y_test)

(912    11.385092
 373    11.719940
 20     12.692503
 800    12.206073
 152    12.154779
 Name: SalePrice, dtype: float64,
 array([11.942357, 12.266708, 11.764323, 11.910629, 12.682258],
       dtype=float32))

In [94]:
## Viewing all model evaluation metric values for XGBOOST using tuned hyperparameters 

result_xg_traintest_hyperparamtune =pd.DataFrame({'model_score': [get_model_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=2000,min_child_weight=3,max_depth=8,
                                                                gamma=0.1,colsample_bytree=0.3),X_train,X_test,y_train,y_test)],
                                       
                                                  'r2_score':[get_r2_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=2000,min_child_weight=3,max_depth=8,
                                                                gamma=0.1,colsample_bytree=0.3),X_train,X_test,y_train,y_test)],
                                                  
                                                  'rmse':[get_rmse_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=2000,min_child_weight=3,max_depth=8,
                                                                gamma=0.1,colsample_bytree=0.3),X_train,X_test,y_train,y_test)],
                                                  
                                                  'mae':[get_mae_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=2000,min_child_weight=3,max_depth=8,
                                                                gamma=0.1,colsample_bytree=0.3),X_train,X_test,y_train,y_test)]},
                                       
                                                  index=['XGBOOST Hyperparameter Tuned'])



model_score  r2_score     rmse       mae
XGBOOST Hyperparameter Tuned     0.901701  0.901701  0.12808  0.095006

#### Fitting Randomized Search CV to X,y directly(Without usung train test split)

In [107]:
xgboost_randomcv=RandomizedSearchCV(XGBRegressor(),param_distributions=params_xgboost,n_iter=4,n_jobs=1,cv=3,verbose=3)

xgboost_randomcv.fit(X,y)

Fitting 10 folds for each of 20 candidates, totalling 200 fits
[CV] n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3, score=0.881, total=   0.8s
[CV] n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.7s remaining:    0.0s


[CV]  n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3, score=0.896, total=   0.8s
[CV] n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3 


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.5s remaining:    0.0s


[CV]  n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3, score=0.897, total=   0.7s
[CV] n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3 
[CV]  n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3, score=0.856, total=   0.7s
[CV] n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3 
[CV]  n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3, score=0.892, total=   0.7s
[CV] n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3 
[CV]  n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3, score=0.894, total=   0.7s
[CV] n_estimators=1000, min_child_weight=7, max_depth=10, learning_rate=0.25, gamma=0.2, colsample_bytree=0.3 


[Parallel(n_jobs=1)]: Done 200 out of 200 | elapsed:  3.8min finished


RandomizedSearchCV(cv=10,
                   estimator=XGBRegressor(base_score=None, booster=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, gamma=None,
                                          gpu_id=None, importance_type='gain',
                                          interaction_constraints=None,
                                          learning_rate=None,
                                          max_delta_step=None, max_depth=None,
                                          min_child_weight=None, missing=nan,
                                          monotone_constraints=None,
                                          n_estimators=100,...
                                          scale_pos_weight=None, subsample=None,
                                          tree_method=None,
                                          validate

#### FINDING THE BEST PARAMETER VALUES FOR DIFFERENT 'n_iter' AND 'cv'

In [164]:
xgboost_randomcv.best_params_  ## n_iter=4, cv=3   

{'n_estimators': 1000,
 'min_child_weight': 1,
 'max_depth': 6,
 'learning_rate': 0.05,
 'gamma': 0.1,
 'colsample_bytree': 0.3}

#### Applying tuned hyper parameters using Cross Validation technique for Xgboost

In [165]:
## n_iter=4, cv=3

cross_val_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=1000,min_child_weight=1,
                            max_depth=6,gamma=0.1,colsample_bytree=0.3),X,y,cv=10).mean()

0.8938852889704207

In [95]:
## Converting cross validation score of XGBOOST model with tuned hyperparameters into dataframe

result_xg_crossval_hyperparamtune =pd.DataFrame({'cross_val_score': [cross_val_score(XGBRegressor(learning_rate=0.05,random_state=10,n_estimators=1000,min_child_weight=1,
                                                                    max_depth=6,gamma=0.1,colsample_bytree=0.3),X,y,cv=10).mean()]},
                                       index=['XGBOOST Hyperparameter Tuned'])


In [96]:
## Viewing all the model evaluation metric values and cross validation score for XGBOOST 
## using tuned hyperparameters

result_xg_hyperparamtune=pd.concat([result_xg_traintest_hyperparamtune,result_xg_crossval_hyperparamtune],
                                    axis=1)

result_xg_hyperparamtune

model_score  r2_score     rmse       mae  \
XGBOOST Hyperparameter Tuned     0.901701  0.901701  0.12808  0.095006   

                              cross_val_score  
XGBOOST Hyperparameter Tuned         0.893885

### HYPERARAMETER OPTIMIZATION FOR SVR

In [97]:
# Applying Grid Search to find the best model and the best parameters #C--0.1 to 1000 #gamma---0.01 to 10

params_svr = [{'C': [1,2,3,4,5,6,7,8,9, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]



print(params_svr)


[{'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100, 1000], 'kernel': ['linear']}, {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]


### Fitting Randomized Search CV For Train Test Split data

In [46]:
svr_randomcv=RandomizedSearchCV(SVR(),param_distributions=params_svr,n_iter=4,n_jobs=1,cv=3,verbose=3)

svr_randomcv.fit(X_train,y_train)

Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] kernel=linear, C=3 ..............................................
[CV] .................. kernel=linear, C=3, score=0.883, total=   0.1s
[CV] kernel=linear, C=3 ..............................................
[CV] .................. kernel=linear, C=3, score=0.845, total=   0.1s

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s



[CV] kernel=linear, C=3 ..............................................
[CV] .................. kernel=linear, C=3, score=0.872, total=   0.1s
[CV] kernel=linear, C=1000 ...........................................
[CV] ............... kernel=linear, C=1000, score=0.884, total=   7.6s
[CV] kernel=linear, C=1000 ...........................................
[CV] ............... kernel=linear, C=1000, score=0.846, total=  10.6s
[CV] kernel=linear, C=1000 ...........................................
[CV] ............... kernel=linear, C=1000, score=0.872, total=   8.5s
[CV] kernel=rbf, gamma=0.6, C=1 ......................................
[CV] .......... kernel=rbf, gamma=0.6, C=1, score=0.849, total=   0.1s
[CV] kernel=rbf, gamma=0.6, C=1 ......................................
[CV] .......... kernel=rbf, gamma=0.6, C=1, score=0.863, total=   0.0s
[CV] kernel=rbf, gamma=0.6, C=1 ......................................
[CV] .......... kernel=rbf, gamma=0.6, C=1, score=0.829, total=   0.0s
[CV] 

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:   27.2s finished


RandomizedSearchCV(cv=3, estimator=SVR(), n_iter=4, n_jobs=1,
                   param_distributions=[{'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                                               100, 1000],
                                         'kernel': ['linear']},
                                        {'C': [1, 10, 100, 1000],
                                         'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6,
                                                   0.7, 0.8, 0.9],
                                         'kernel': ['rbf']}],
                   verbose=3)

#### FINDING THE BEST PARAMETER VALUES FOR DIFFERENT 'n_iter' AND 'cv'

In [47]:
svr_randomcv.best_params_ ## BEST

{'kernel': 'linear', 'C': 1000}

#### Applying tuned hyper parameters using train test split technique for SVR

In [48]:
## Calculating the model score using tuned hyperparameters  # C=1000,kernel='linear' ## BEST

get_model_score(SVR(C=1000,kernel='linear'),X_train,X_test,y_train,y_test)

0.9052214608116056

In [98]:
## Calculating r2_score for the model using tuned hyperparameters

get_r2_score(SVR(C=1000,kernel='linear'),X_train,X_test,y_train,y_test)

0.9052214608116056

In [99]:
## Calculating rmse score for the model using tuned hyperparameters

get_rmse_score(SVR(C=1000,kernel='linear'),X_train,X_test,y_train,y_test)

0.12576611526526232

In [100]:
## Calculating mean absolute error for the model using tuned hyperparameters

get_mae_score(SVR(C=1000,kernel='linear'),X_train,X_test,y_train,y_test)

0.09536301388646762

In [101]:
## Displaying and comparing y_train and y_predict values using tuned hyperparameters

get_y_train_y_predict(SVR(C=1000,kernel='linear'),X_train,X_test,y_train,y_test)

(912    11.385092
 373    11.719940
 20     12.692503
 800    12.206073
 152    12.154779
 Name: SalePrice, dtype: float64,
 array([12.02443227, 12.32583964, 11.70592666, 11.91274209, 12.66676045]))

In [102]:
## Viewing all model evaluation metric values for SVR using tuned hyperparameters 

result_SVR_traintest_hyperparamtune =pd.DataFrame({'model_score': [get_model_score(SVR(C=1000,kernel='linear'),X_train,X_test,y_train,y_test)],
                                       
                                                  'r2_score':[get_r2_score(SVR(C=1000,kernel='linear'),X_train,X_test,y_train,y_test)],
                                                  
                                                  'rmse':[get_rmse_score(SVR(C=1000,kernel='linear'),X_train,X_test,y_train,y_test)],
                                                  
                                                  'mae':[get_mae_score(SVR(C=1000,kernel='linear'),X_train,X_test,y_train,y_test)]},
                                       
                                                  index=['SVR Hyperparameter Tuned'])


model_score  r2_score      rmse       mae
SVR Hyperparameter Tuned     0.905221  0.905221  0.125766  0.095363

#### Fitting Randomized Search CV to X,y directly(Without usung train test split)

In [103]:
svr_randomcv=RandomizedSearchCV(SVR(),param_distributions=params_svr,n_iter=4,n_jobs=1,cv=3,verbose=3)

svr_randomcv.fit(X,y)

Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] kernel=rbf, gamma=0.5, C=10 .....................................
[CV] ......... kernel=rbf, gamma=0.5, C=10, score=0.877, total=   0.1s
[CV] kernel=rbf, gamma=0.5, C=10 .....................................
[CV] ......... kernel=rbf, gamma=0.5, C=10, score=0.856, total=   0.1s
[CV] kernel=rbf, gamma=0.5, C=10 .....................................
[CV] ......... kernel=rbf, gamma=0.5, C=10, score=0.853, total=   0.1s
[CV] kernel=rbf, gamma=0.5, C=1 ......................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV] .......... kernel=rbf, gamma=0.5, C=1, score=0.893, total=   0.0s
[CV] kernel=rbf, gamma=0.5, C=1 ......................................
[CV] .......... kernel=rbf, gamma=0.5, C=1, score=0.867, total=   0.0s
[CV] kernel=rbf, gamma=0.5, C=1 ......................................
[CV] .......... kernel=rbf, gamma=0.5, C=1, score=0.867, total=   0.0s
[CV] kernel=rbf, gamma=0.8, C=1000 ...................................
[CV] ....... kernel=rbf, gamma=0.8, C=1000, score=0.859, total=   0.1s
[CV] kernel=rbf, gamma=0.8, C=1000 ...................................
[CV] ....... kernel=rbf, gamma=0.8, C=1000, score=0.823, total=   0.1s
[CV] kernel=rbf, gamma=0.8, C=1000 ...................................
[CV] ....... kernel=rbf, gamma=0.8, C=1000, score=0.831, total=   0.1s
[CV] kernel=rbf, gamma=0.5, C=1000 ...................................
[CV] ....... kernel=rbf, gamma=0.5, C=1000, score=0.853, total=   0.1s
[CV] kernel=rbf, gamma=0.5, C=1000 ...................................
[CV] .

[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.7s finished


RandomizedSearchCV(cv=3, estimator=SVR(), n_iter=4, n_jobs=1,
                   param_distributions=[{'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                                               100, 1000],
                                         'kernel': ['linear']},
                                        {'C': [1, 10, 100, 1000],
                                         'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6,
                                                   0.7, 0.8, 0.9],
                                         'kernel': ['rbf']}],
                   verbose=3)

#### FINDING THE BEST PARAMETER VALUES FOR DIFFERENT 'n_iter' AND 'cv'

In [104]:
svr_randomcv.best_params_

{'kernel': 'rbf', 'gamma': 0.5, 'C': 1}

#### Applying tuned hyper parameters using Cross Validation technique for Xgboost

In [105]:
# n_iter=4,cv=3

cross_val_score(SVR(C=1,gamma=0.5,kernel='rbf'),X,y,cv=10)

array([0.89391918, 0.91190067, 0.89412472, 0.87295951, 0.87805413,
       0.89987745, 0.87228209, 0.87809508, 0.86433445, 0.86394629])

In [106]:
cross_val_score(SVR(C=1,gamma=0.5,kernel='rbf'),X,y,cv=10).mean()

0.8829493583309842

In [108]:
## Converting cross validation score of SVR model with tuned hyperparameters into dataframe

result_SVR_crossval_hyperparamtune =pd.DataFrame({'cross_val_score': [cross_val_score(SVR(C=1,gamma=0.5,kernel='rbf'),X,y,cv=10).mean()]},
                                       index=['SVR Hyperparameter Tuned'])

In [109]:
## Viewing all the model evaluation metric values and cross validation score for SVR 
## using tuned hyperparameters

result_SVR_hyperparamtune=pd.concat([result_SVR_traintest_hyperparamtune,result_SVR_crossval_hyperparamtune],
                                    axis=1)

result_SVR_hyperparamtune

model_score  r2_score      rmse       mae  \
SVR Hyperparameter Tuned     0.905221  0.905221  0.125766  0.095363   

                          cross_val_score  
SVR Hyperparameter Tuned         0.882949

In [112]:
## Viewing and comparing all the model evaluation metrics values of different models with hyperparameter optimization

result_with_hyperparamtune_rf_xg_SVR=pd.concat([result_rf_hyperparamtune,result_xg_hyperparamtune,result_SVR_hyperparamtune],
                                     axis=0)

result_with_hyperparamtune_rf_xg_SVR

model_score  r2_score      rmse       mae  \
Random Forest Hyperparameter Tuned     0.887049  0.887049  0.137295  0.096988   
XGBOOST Hyperparameter Tuned           0.901701  0.901701  0.128080  0.095006   
SVR Hyperparameter Tuned               0.905221  0.905221  0.125766  0.095363   

                                    cross_val_score  
Random Forest Hyperparameter Tuned         0.887423  
XGBOOST Hyperparameter Tuned               0.893885  
SVR Hyperparameter Tuned                   0.882949

In [181]:
## Viewing and comparing all the model evaluation metrics values of different models without hyperparameter optimization

result_without_hyperparamtune_rf_xg_SVR=result_without_hyperparamtune.loc[['Random Forest','XGBOOST','SVR','Linear Regression'],:]

## Renaming the rows/indexes

result_without_hyperparamtune_rf_xg_SVR.index=['Random Forest Without Hyperparameter Tune',
                                              'XGBOOST Without Hyperparameter Tune',
                                              'SVR Without Hyperparameter Tune',
                                              'Linear Regression Without Hyperparameter Tune']

result_without_hyperparamtune_rf_xg_SVR

model_score  r2_score  \
Random Forest Without Hyperparameter Tune         0.878067  0.878067   
XGBOOST Without Hyperparameter Tune               0.903941  0.903941   
SVR Without Hyperparameter Tune                   0.894999  0.894999   
Linear Regression Without Hyperparameter Tune     0.904519  0.904519   

                                                   rmse       mae  \
Random Forest Without Hyperparameter Tune      0.142649  0.103198   
XGBOOST Without Hyperparameter Tune            0.126613  0.093910   
SVR Without Hyperparameter Tune                0.132375  0.100170   
Linear Regression Without Hyperparameter Tune  0.126232  0.096170   

                                               cross_val_score  
Random Forest Without Hyperparameter Tune             0.874137  
XGBOOST Without Hyperparameter Tune                   0.891533  
SVR Without Hyperparameter Tune                       0.886948  
Linear Regression Without Hyperparameter Tune         0.880901

### STACKING ENSEMBLE

## base=rf,xg,lin  meta=svr

In [25]:
## Defining the base models

level0=list()

level0.append(('rf',RandomForestRegressor(n_estimators= 2000,min_samples_split= 2,min_samples_leaf= 1,
                                      max_features= 'sqrt',max_depth= 340,random_state=10)))

level0.append(('lr',LinearRegression()))

In [26]:
## Defining meta learner model

level1=SVR(C=1000,kernel='linear')

In [27]:
## Defining stacking ensemble  ## check Shift+Tab for details ## for base- rf,xg,linear meta=svr

stacking_model=StackingRegressor(estimators=level0,final_estimator=level1,cv=10)

#### Fitting the Stacked Ensembled Model to train_test_split data

In [215]:
stacking_model.fit(X_train,y_train)

StackingRegressor(cv=10,
                  estimators=[('rf',
                               RandomForestRegressor(max_depth=340,
                                                     max_features='sqrt',
                                                     n_estimators=2000,
                                                     random_state=10)),
                              ('lr', LinearRegression())],
                  final_estimator=SVR(C=1000, kernel='linear'))

#### Using Stacked Ensemble Model and calculating the different evaluation metric values BASE=rf,xg,linear  META=svr

In [216]:
## Calculating the model score using Stacked Ensemble model

get_model_score(stacking_model,X_train,X_test,y_train,y_test)  ## with  rf linear  svr ## BEST

0.9093325077824626

In [217]:
## Calculating r2_score for the model using Stacked Ensemble model

get_r2_score(stacking_model,X_train,X_test,y_train,y_test)

0.9093325077824626

In [218]:
## Calculating rmse score for the model using Stacked Ensemble model

get_rmse_score(stacking_model,X_train,X_test,y_train,y_test)

0.12300830747678204

In [219]:
## Calculating mean absolute error for the model using Stacked Ensemble model

get_mae_score(stacking_model,X_train,X_test,y_train,y_test)

0.09292279281899297

In [220]:
## Displaying and comparing y_train and y_predict values using Stacked Ensemble model

get_y_train_y_predict(stacking_model,X_train,X_test,y_train,y_test)

(912    11.385092
 373    11.719940
 20     12.692503
 800    12.206073
 152    12.154779
 Name: SalePrice, dtype: float64,
 array([11.99134391, 12.30971798, 11.71429262, 11.88284453, 12.70549393]))

#### Fitting the Stacked Ensemble Model to the entire data

In [28]:
stacking_model.fit(X,y)

StackingRegressor(cv=10,
                  estimators=[('rf',
                               RandomForestRegressor(max_depth=340,
                                                     max_features='sqrt',
                                                     n_estimators=2000,
                                                     random_state=10)),
                              ('lr', LinearRegression())],
                  final_estimator=SVR(C=1000, kernel='linear'))

#### Using Stacked Ensemble Model and calculating the Cross Validation Score of the model

In [222]:
cross_val_score(stacking_model,X,y,cv=10)

array([0.88711299, 0.912706  , 0.90739987, 0.87752946, 0.88524926,
       0.90054868, 0.89699589, 0.90690546, 0.87384598, 0.87422707])

In [223]:
cross_val_score(stacking_model,X,y,cv=10).mean()

0.8922520663870401

In [2]:
## From above modeling we can see that the model 'STACKING_MODEL' is giving us the best result regarding modelscore,r2 score
## rmse and mae